### ISSUE TITLE
Improvements : Add custom urls, add open source libraries information

### ISSUE THREAD

**Issue by benju69** [medyo/android-about-page#1]

**Comment by medyo** [comment]
Hi @benju69,

What do you mean by 'custom urls', because the current version supports custom url intents  ?

**Comment by Souf-R** [comment]
Hi @medyo 

I think it would be better to use a list of pairs (_library name, library URL_) like the way **Trello** is doing it in its About page.
Is this what you mean @benju69 ?

**Comment by rfgamaral** [comment]
Yes! I always credit all the third-party libraries I use on my apps on the About page, it's the least we can do for those developers. And this project is actually a perfect example. It's open-source and we can't even credit it properly.

Please consider this issue for a future version.

**Comment by medyo** [comment]
Okay Guys,

Well `android-about-page` was made in a generic way to let developers the full freedom to plug whatever views they like.

To mention `third-party libraries`, there are many libraries solving exactly this point like :

* https://github.com/PSDev/LicensesDialog by @PSDev
* https://github.com/mikepenz/AboutLibraries by @mikepenz

You could easily add a row `Open source libraries` and point it the right activity which implement one of libraries mentioned above.

If you'd like to stick with my library, you could also archieve the same result by doing something like : 

~~~java
AboutPage aboutPage = new AboutPage(this);
aboutPage.addGroup("Open Source libraries");

HashMap<String, String> librariesList = new HashMap<>();
librariesList.put("Fancy Buttons", "https://github.com/medyo/Fancybuttons");
librariesList.put("Once", "https://github.com/jonfinerty/Once");
librariesList.put("Android Iconics", "https://github.com/mikepenz/Android-Iconics");

for (Map.Entry<String, String> lib : librariesList.entrySet()) {
    Element libElement = new Element();
    libElement.setTitle(lib.getKey());

    Intent libIntent = new Intent(Intent.ACTION_VIEW,Uri.parse(lib.getValue()));
    libElement.setIntent(libIntent);

    aboutPage.addItem(libElement);
}

View viewAboutPage = aboutPage.create();
~~~

![Open Source Libraries](https://www.dropbox.com/s/7nqh67vem8xllc0/open-source-libraries.png?dl=1&random=35)

**Comment by medyo** [comment]
I'll close this issue, if you've any other questions, just reopen

Thanks

**Comment by benju69** [comment]
Ok cool :) Thanks for the example
