### ISSUE TITLE
Links not working on android < 6.0 M

### ISSUE THREAD

**Issue by gugakatsi** [medyo/android-about-page#100]
should i handle links myself ? they don't seem to work on  < 6.0 versions , on N and etc works fine .

**Comment by medyo** [comment]
Hi @gugakatsi,

We only support famous apps like Facebook, Instagram ... If you'd like to add a custom app or link, just override the onClickListener for the element and create an intent there

**Comment by gugakatsi** [comment]
@medyo not even Fb, or instagram links work , i am using with v4 fragment , could it be a problem?

**Comment by medyo** [comment]
Could you share a sample of your code

**Comment by gugakatsi** [comment]
`
import android.os.Bundle
import android.support.v4.app.Fragment
import android.view.Gravity
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import mehdi.sakout.aboutpage.AboutPage
import mehdi.sakout.aboutpage.Element
import pimpify.gone.R


/*
 *  About app static activity
 */
class AboutAppFragment : Fragment() {

    companion object {
        fun newInstance() = AboutAppFragment()
    }

    override fun onCreateView(inflater: LayoutInflater?, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {

        val footerElement = Element().setTitle(getString(R.string.footer_text))
                                     .setGravity(Gravity.LEFT)
        val versionElement = Element().setTitle("v 1.0 ბეტა")

        /* TODO convert website and those values to res */
        return AboutPage(activity.baseContext)
                    .setCustomFont("fonts/tbc.ttf")
                    .isRTL(false)
                    .setImage(R.drawable.ic_uniguide_logo)
                    .setDescription(getString(R.string.about))
                    .addGroup("აპლიკაციის ვერსია")
                    .addItem(versionElement)
                    .addGroup(getString(R.string.contact_us))
                    .addEmail("support@uniguide.ge","ელ-ფოსტა")
                    .addWebsite("https://www.uniguide.ge/", getString(R.string.about_website))
                    .addFacebook("Uniguide.ge", getString(R.string.about_facebook))
                    .addTwitter("UniguideApp", getString(R.string.about_twitter))
                    .addPlayStore("pimpify.gone", getString(R.string.about_play_store))
                    .addInstagram("uniguideApp", getString(R.string.about_instagram))
                    .create()
    }

}`

**Comment by medyo** [comment]
Unfortunately, the library doesn't support fragment integration.
Try to use a custom view or an activity.

**Comment by gugakatsi** [comment]
@medyo thanks for fast and helpful responses.
