### ISSUE TITLE
Is it possible to override default strings?

### ISSUE THREAD

**Issue by ardevd** [medyo/android-about-page#104]
Currently, the predefined about page items such as addPlayStore() , addGitHub(), etc have pre-determined texts such as "Fork us on Github". What's the easiest way to override these strings? In my case I'm a indie developer so using the term "us" doesnt really make sense. 

Cheers!

**Comment by medyo** [comment]
Just call `addFacebook(String id, String title)`, every provider setter has two parameters, an id and a custom string if defined

**Comment by ardevd** [comment]
Awesome. Not sure how I missed that! Thanks.
