### ISSUE TITLE
Dark mode / Light mode

### ISSUE THREAD

**Issue by Tvax** [medyo/android-about-page#113]
How does is set the background color (Dark or Light)?
Because launching the same app with the same style on different phones results in different background colors.
So, is there any way to set a constant defining the theme to the light one?

**Comment by tatocaster** [comment]
@medyo anything about it?

**Comment by Dararii** [comment]
just download the library and comment every night color in res/color. So that you can always get day color, and vice versa.

**Comment by Tvax** [comment]
Ok thank you, that's a fix, but that's not so clean

**Comment by tatocaster** [comment]
this is not a fix. it is a workaround.

**Comment by kord123** [comment]
Just add this line to the fragment/activity where you create about page:
`AppCompatDelegate.setDefaultNightMode(MODE_NIGHT_NO)
`

**Comment by nikothegreek** [comment]
> Just add this line to the fragment/activity onCreate where you create about page:
> `AppCompatDelegate.setDefaultNightMode(MODE_NIGHT_NO) `

@kord123 I tried to use it but on every app start the app restarts once again some my onCreate Method of my called fragment are always called twice, how can I solve it?? Didn't find any solutions online.

**Comment by medyo** [comment]
Hi,
I just made the dark mode optional, it's up to the user developer to force it or not.
Please check if this fixes your issue so I could merge it with the master

**Comment by nikothegreek** [comment]
> Hi,
> I just made the dark mode optional, it's up to the user developer to force it or not.
> by calling
> 
> ```
> View aboutPage = new AboutPage(this)
>                 .enableDarkMode(false) // or true
> ```
> 
> Please check if this fixes your issue so I could merge it with the master

Oh man, this feature would be sooo nice so I don't have to work with the app wide dark mode.

How exactly can I test it? I've never worked with multiple branches before.

**Comment by medyo** [comment]
@nikothegreek 
Okay, I'll deploy it as beta so others can test it too

**Comment by nikothegreek** [comment]
No, if it's more work you don't have to...

**Comment by medyo** [comment]
That's okay, here is the beta version 
`implementation 'com.github.medyo:android-about-page:1.3-beta'`

**Comment by nikothegreek** [comment]
At least for my purposes it it working well.
Thanks for including it, I appreciate it!

**Comment by malayaliscorner** [comment]
Thanks but please do a workaround for MIUI Dark mode,the about page is still dark on MIUI with .enableDarkMode(false) code.
