### ISSUE TITLE
Website support

### ISSUE THREAD

**Issue by skmlcd** [medyo/android-about-page#12]
I know it's really easy to add custom item, but maybe in the future you could add predefined website item support. I don't know how useful this really would be, you would use some generic icon for website (like with Facebook/Twitter/Instagram) since every website has their own icon/branding.

Maybe something like this:
`.addWebsite("http://google.com") // uses generic icon`
`.addWebsite("http://google.com", R.mipmap.my_website_icon) // uses specific icon`

**Comment by medyo** [comment]
it's already made by @filipmaelbrancke, I'll check his pull request #7 and merge it.

**Comment by skmlcd** [comment]
Oh sorry, I didn't check pull requests. Great job!
