### ISSUE TITLE
AndroidX Jetpack migration needed

### ISSUE THREAD

**Issue by anggrayudi** [medyo/android-about-page#126]
Well, I think we need to publish this library with AndroidX Jetpack ASAP. I checked so many dependencies on my project, and found that 3 of 19 dependencies are still using old Support Library. Android About Page is one of them. I am aware that this lib will cause crash to my app since Support Library has different package name with AndroidX Jetpack. We don't have to wait until stable version 1.0.0 is released by Google. We can do it now. I have tested AndroidX and found no problem with it.

**Comment by medyo** [comment]
Hi @anggrayudi,

Could you propose a pull request of the migration?

**Comment by anggrayudi** [comment]
Hi @medyo , I'll try. But I can't do it this week because I am extremely busy now. I'll migrate this library when I am done.

**Comment by medyo** [comment]
Library upgraded to androidX
