### ISSUE TITLE
Why market place

### ISSUE THREAD

**Issue by HBiSoft** [medyo/android-about-page#132]
It doesn't look like this library is still active, but anyway. You are using market place (which is old and not used anymore):

    Uri uri = Uri.parse("market://details?id=" + id);
    Intent goToMarket = new Intent(Intent.ACTION_VIEW, uri);
    playStoreElement.setIntent(goToMarket);

You should use Play Store instead:

    Uri uri = Uri.parse("https://play.google.com/store/apps/details?id=" + id);
    Intent goToMarket = new Intent(Intent.ACTION_VIEW, uri);
    playStoreElement.setIntent(goToMarket);

By leaving it as it is, it will display a popup message for most devices saying `To view this content install and setup a web browsing app`

**Comment by medyo** [comment]
Hi @HBiSoft,

Please do a pull request so I can merge it
Thank you

**Comment by medyo** [comment]
Fixed and merged
