### ISSUE TITLE
Incorrect image color, iconDrawable is dark

### ISSUE THREAD

**Issue by Wiktorl4z** [medyo/android-about-page#139]
Hi,
I want to add my custom image.
```
val discordElement = Element()
discordElement.title = "Discord"
discordElement.iconDrawable = R.drawable.discord
```
![image](https://user-images.githubusercontent.com/16363930/78407931-3340fd80-7606-11ea-90db-fd2c9bcb8dae.png)

Image is png file with colors on transparent background.
After installing apk image is dark.

**Comment by medyo** [comment]
@Wiktorl4z Try a Vector Drawable icon, it's available here: https://materialdesignicons.com/
