### ISSUE TITLE
Can't Implement Image as Web link

### ISSUE THREAD

**Issue by malayaliscorner** [medyo/android-about-page#150]
I tried this to code to create a web link from the image,But it isn't working,
 
```
setImage.setOnClickListener {
            val intent = Intent(Intent.ACTION_VIEW)
            intent.data = Uri.parse("https://www.google.com")
            startActivity(intent)}
```

**Comment by medyo** [comment]
Hi @malayaliscorner,
Please post the `setImage` code too so I can reproduce the issue
Thank you

**Comment by malayaliscorner** [comment]
The normal code

 ```
 val aboutPage = AboutPage(this)
            .addGroup("Support Us")
            .setImage(com.malayalam.funnytrollaudios.R.drawable.me)
```
And thanks for intsant help...

**Comment by medyo** [comment]
`clickListener` is only bindable to `Element` objects, you can't bind it to the `about page imageview`,
please refer to this section for more details
https://github.com/medyo/android-about-page#5-available-attributes-for-element-class
