### ISSUE TITLE
Auto night mode support

### ISSUE THREAD

**Issue by ardevd** [medyo/android-about-page#151]
I believe this library previously supported auto night mode. Meaning, if the device was set to night mode, the about page would display in night mode. It seems like we now have to explicitly specify whether we want night mode in the builder.

Any chance to get support for auto night mode?

**Comment by medyo** [comment]
Yes, that was the previous behaviour.

You can explicitly auto-enable the dark mode by doing:

```
val nightModeFlags = getContext().getResources().getConfiguration().uiMode &
    Configuration.UI_MODE_NIGHT_MASK
val nightModeEnabled = nightModeFlags == Configuration.UI_MODE_NIGHT_YES) 
View aboutPage = new AboutPage(this)
  .isRTL(false)
  .enableDarkMode(nightModeEnabled)
  ...
```

**Comment by ardevd** [comment]
Thanks. This is what I'm currently doing as well. Works well enough.
