### ISSUE TITLE
Only in English?

### ISSUE THREAD

**Issue by Isabellle** [medyo/android-about-page#16]
I just gave a try to your great-looking plugin.
Am I wrong or we can't change/edit labels to another language?
Also, where is the long description located? 

Great work by the way ;)

**Comment by medyo** [comment]
Hi @Isabellle, we're working on the Localization, it'll be available as soon as possible.
We still looking for the best way to handle it, more details #15.

We'll need your help too for the belgium translation, if you're okay with that.

About the description, You could change it by calling `setDescription(String)` or overriding the `<string name="about_page_description"></string>`

**Comment by Isabellle** [comment]
I'm totally available to provide you with french translations (In Belgium, we speak french, dutch and german - I'm native french)

Thank you for your answer

**Comment by medyo** [comment]
Now we do support Italian and Belgian, could you make translations for french and dutch ?

Check this example : https://github.com/medyo/android-about-page/blob/master/library/src/main/res/values-de/strings.xml

**Comment by skmlcd** [comment]
So it only needs to be extra directory with language code at the end and inside translated strings.xml?

Since German and Italian are already translated, I'm going to make Slovenian and Croatian translations.

**Comment by medyo** [comment]
Yes, that's it. More details on : http://developer.android.com/intl/ja/training/basics/supporting-devices/languages.html

**Comment by skmlcd** [comment]
Is it alright that I leave Fork? In our language there is no correct translation and we would usually leave the English work in place. I have seen that German translation is the same, but other languages did translate it.

**Comment by geecko86** [comment]
Funny to see another Belgian here.

I would suggest using Crowdin, a crowdsourced translation platform which is free for Open Source projects. It makes it easy to invite new translators.

**Comment by medyo** [comment]
@Isabellle, the french language is now available
