### ISSUE TITLE
Resource prefix for library module

### ISSUE THREAD

**Issue by vanniktech** [medyo/android-about-page#17]
Would be cool if every resource would be prefixed to avoid duplicates.

There's a handy Gradle property for that `resourcePrefix 'my_prefix'` and lint checks that every resource is prefixed.

**Comment by medyo** [comment]
Seems cool, first time I hear about 'resourcePrefix' property, could you make a pull request for it ?

**Comment by vanniktech** [comment]
Sure which name would you like? `android_about_page`?

**Comment by medyo** [comment]
I've already used `about` as prefix for strings, I think we can keep it
