### ISSUE TITLE
Centered Image and Left Aligned description looks bit off

### ISSUE THREAD

**Issue by sagarsiddhpura** [medyo/android-about-page#23]
In in non RTL mode, image is centered and description is left aligned looks non-symmetric. It would be very helpful if we could provide alignment on description. Please see screenshot: http://imgur.com/Mlabuq1

**Comment by skmlcd** [comment]
Some image customization options would be nice :+1:

**Comment by medyo** [comment]
The description is now centred #62a6f3b
