### ISSUE TITLE
how do you add it in fragment

### ISSUE THREAD

**Issue by StartappzKE** [medyo/android-about-page#3]
public class InspireFragment extends Fragment {
    public static final String TAG = MainActivity.class.getSimpleName();
    
    TextView textView;

    ArrayAdapter<String> adapter;
    ArrayList<String> items;
    static String youtube_code;
    SwipeRefreshLayout mSwipeRefreshLayout;
    private String tag_string_req = "string_req";
    View v;
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
         v = inflater.inflate(R.layout.about_inspire, container, false);

        TextView textView = (TextView) v.findViewById(R.id.txtLarge);
        textView.setTypeface(MainActivity.arialface);

        Element versionElement = new Element();
        versionElement.setTitle("Version 6.2");

        Element adsElement = new Element();
        adsElement.setTitle("Advertise with us");

        View aboutPage = new AboutPage(getActivity())
                .isRTL(false)
                .setImage(R.drawable.about_icon_instagram)
                .addItem(versionElement)
                .addItem(adsElement)
                .addGroup("Connect with us")
                .addEmail("elmehdi.sakout@gmail.com")
                .addFacebook("the.medy")
                .addTwitter("medyo80")
                .addYoutube("UCdPQtdWIsg7_pi4mrRu46vA")
                .addPlayStore("com.ideashower.readitlater.pro")
                .create();

        setContentView(aboutPage);    // shows error in fragment

        return v;
    }

}

**Comment by medyo** [comment]
because `setContentView` is an `Activity` method !
For fragments, things are different, you should return the view instead : 
```
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
     View aboutPage = new AboutPage(getContext())....
     return aboutPage;
}
```

**Comment by StartappzKE** [comment]
Worked thanks

**Comment by Hi1talib1World** [comment]
try
` Element adsElement = new Element();
  adsElement.setTitle("Advertise with us");

        View aboutPage = new AboutPage(getActivity())
                .isRTL(false)
                .addItem(versionElement)
                .addItem(adsElement)
                .addGroup("Connect with us")
                .addEmail("elmehdi.sakout@gmail.com")
                .addFacebook("the.medy")
                .addTwitter("medyo80")
                .addYoutube("UCdPQtdWIsg7_pi4mrRu46vA")
                .addPlayStore("com.ideashower.readitlater.pro")
                .addInstagram("medyo80")
                .addGitHub("medyo")
                .create();

        viewGroup.addView(aboutPage);
        return viewGroup;
    }`
