### ISSUE TITLE
Image customization options

### ISSUE THREAD

**Issue by skmlcd** [medyo/android-about-page#34]
Any plans to add some branding image customization options, like width and height?

Something like:

```java
// default size, only image resource
.setImage(int);

// image resource, width, height (in DP)
.setImage(int, int, int);
```

**Comment by medyo** [comment]
I Think there is no need to go into such details, The library is made generic with the minimum code as possible so the developer could easily tweak his app just by overriding any resources.

Here is a sample : 

~~~xml
<style name="about_image">
        <item name="android:layout_width">mySize</item>
        <item name="android:layout_height">mySize</item>
....
    </style>
~~~

**Comment by skmlcd** [comment]
You're right, sorry I didn't check how it was implemented. I just assumed it was hard-coded.

Overwriting style works too.
