### ISSUE TITLE
Support mimaps

### ISSUE THREAD

**Issue by addrum** [medyo/android-about-page#43]
Android now recommends to use mipmaps for icons, would be nice if .setIcon supports mipmaps as well as drawables.

**Comment by medyo** [comment]
Hi @addrum,

I think `mipmaps` are only reserved for launcher icons, because they are used at resolutions different from the device’s current density, source : http://android-developers.blogspot.co.uk/2014/10/getting-your-apps-ready-for-nexus-6-and.html

**Comment by addrum** [comment]
@medyo I know, but I'd like to be able to use my launcher icon as the seticon image. Would this cause issues in displaying it in an activity?

**Comment by medyo** [comment]
okay @addrum, I'll add a new setter supporting mipmap as parameter, it'll be available in the coming version

**Comment by addrum** [comment]
Thanks!

**Comment by medyo** [comment]
@addrum, I just pushed the new version, I've only added a new setter to enable/disable coloring the icon. This, will work perfectly for you.

~~~java
new Element().setTitle("Version 6.2").setIcon(R.mipmap.ic_launcher).setAutoIconColor(false)
~~~
