### ISSUE TITLE
Remove String

### ISSUE THREAD

**Issue by shafaque** [medyo/android-about-page#45]
![device-2016-05-12-162544](https://cloud.githubusercontent.com/assets/14124472/15212496/9f3d356c-185e-11e6-8009-80c39880a960.png)
how to remove this string?

**Comment by medyo** [comment]
which string ?

**Comment by falcon2010** [comment]
@medyo i think it related to about_page_description  values in library project

**Comment by medyo** [comment]
@shafaque would you like to change it or remove it ?

**Comment by shafaque** [comment]
@medyo Sir, I like to to change the "Lorem ipsum dolor.........placerat id" string..how to do this? I have used   aboutpage.setDescription("Its my app")    but its not working.

**Comment by shafaque** [comment]
I

**Comment by shafaque** [comment]
Its was not showing during hotswapping. After new install its working fine.

**Comment by WadekarSachin** [comment]
how i can remove description
