### ISSUE TITLE
Using in Fragment

### ISSUE THREAD

**Issue by AIOSYM** [medyo/android-about-page#46]
Very good library and convenience to use, but I want to know how to use it in Fragment instead of activity. I am just a beginner, so please help me. Thank you in advance

**Comment by medyo** [comment]
Hi @AIOSYM,

To use the library on a fragment , just implement the same code but instead of calling `new AboutPage(this)`, do `new AboutPage(getActivity())`

**Comment by AIOSYM** [comment]
@medyo Thank you!

**Comment by gugakatsi** [comment]
@medyo instead of setConteview in fragment , i am returning aboutPage view in onCreateView() but still doesn't works . am i doing something wrong.

**Comment by gugakatsi** [comment]
@medyo nvm , fixed it.
