### ISSUE TITLE
Conflict after adding library to the gradle

### ISSUE THREAD

**Issue by AIOSYM** [medyo/android-about-page#49]
My project has NavigationDrawer and everything works fine until I add this library to the gradle. When I build the project the compiler thrown the error message that the class of my NavigationDrawer cannot instantiate. It took me few day to find the bug, finally I decided to remove this library from gradle and thing start to work fine. Have you experienced that? or Am I missing something? Thank in advanced

**Comment by medyo** [comment]
Hi @AIOSYM, please refer to this issue :  #44

**Comment by AIOSYM** [comment]
It works perfectly now! 

Thank for the help
