### ISSUE TITLE
can not see texts 

### ISSUE THREAD

**Issue by ismly** [medyo/android-about-page#5]
I cannot see texts, why?

I can only see image, app description, icons.. and nearlynothing else...
![68747470733a2f2f7777772e64726f70626f782e636f6d2f732f376e7168363776656d38786c6c63302f6f70656e2d736f757263652d6c69627261726965732e706e673f646c3d312672616e646f6d3d3335](https://cloud.githubusercontent.com/assets/16943409/14766389/6b58a076-0a10-11e6-8829-912e487dfd89.png)

**Comment by medyo** [comment]
Hi @ismly,

That's really weird, 

do you override this color by white on your behalf ? `<color name="about_item_text_color">#7c7c7c</color>`

if not, please enable the `Show layout bounds` on your phone/emulator to see if the views are well rendered (attach screenshot here)

Thanks

**Comment by ismly** [comment]
Sorry. I m new to this. But I will explain step by step what I did..;

-wrote "compile...." To Gradle file.
-added new activity to my project.
-wrote these items after onCreate method
-these items means;
 Element versionElement = new Element();
....
...
...
.isRtl(false)
.setImage(R.....)

....


I didnt creat a layout file or detailed aboutPage activity..
Must I add detailed activity page?


24 Nisan 2016 Pazar tarihinde, Mehdi Sakout <notifications@github.com>
yazdı:

**Comment by medyo** [comment]
No, you don't have to create a layout file for the about activity, the library generates automatically the view.

How could I reproduce your issue ?  please share your full code ?

**Comment by ismly** [comment]
Now I am on mobile.. Later inshaallah

24 Nisan 2016 Pazar tarihinde, Mehdi Sakout <notifications@github.com>
yazdı:

**Comment by geftimov** [comment]
I had the same problem , my issue was with the theme.
This library does not work nicely with Theme.AppCompat .
So try setting it to Theme.AppCompat.Light or Theme.AppCompat.Light.DarkActionBar .
Hope this helps.

**Comment by medyo** [comment]
@geftimov could you open a new issue to solve it separately

**Comment by falcon2010** [comment]
The problem coming from setTextAppearance when using the NoActionBar theme or AppCompat 
I think you need to add custom style for lib

**Comment by medyo** [comment]
Thanks to @falcon2010, It's fixed
