### ISSUE TITLE
GPU overdraw optimization

### ISSUE THREAD

**Issue by skmlcd** [medyo/android-about-page#55]
Hey, I know this is minor nitpick, but it looks like the view has background set and this add two whole layers of overdraw.

base layer = no color
1. layer = blue
2. layer = green
3. layer = red

The background should have no color over it. Then the text should have blue color over it. See my screenshot, please ignore black rectangle.

![screenshot_20160613-190749](https://cloud.githubusercontent.com/assets/10860015/16016277/7b2c40e6-319a-11e6-8d4f-71301ca35f32.png)

**Comment by medyo** [comment]
Hi @skmlcd, 
I set a default background color just to avoid conflicts with custom themes or Auto-Switching Day/Night Theme... But I totally agree with your opinion, I may start thinking about gpu optimization in the medium future... there are more urgent features.

Thanks

**Comment by medyo** [comment]
I'll close this moment, we'll review it later

**Comment by skmlcd** [comment]
Alright, no problem since it's kinda trivial issue.
