### ISSUE TITLE
How to implement it correctly

### ISSUE THREAD

**Issue by juandiegoapps** [medyo/android-about-page#56]
Hi. I'm trying to implement this project into mine, to use the About page with my own information on it. Every time I try to implement it, it crashs. I don't know hot to implement it well. How do I have to do it? 

P.S.: I have added the line on build.gradle well.

**Comment by skmlcd** [comment]
Check out this [file](https://github.com/medyo/android-about-page/blob/master/app/src/main/java/mehdi/sakout/aboutpage/sample/MainActivity.java). Very simple example. Basically you need to create a View object and then load it into Activity by using method ```setContentView(aboutPage);```

If it doesn't work then post the crash log here, without that we can't help you.

**Comment by juandiegoapps** [comment]
Yes, but how do I have to add the library folder into my project?

**Comment by skmlcd** [comment]
No need to manually include library. Inside your android project ```app/build.gradle```

At the very bottom of that file you should have something like this:
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.github.medyo:android-about-page:1.0.8'
}

```

**Comment by juandiegoapps** [comment]
Yes, but I need to have the files on my project, or not?

**Comment by juandiegoapps** [comment]
Sorry, but I don't know how to use projects from GitHub, just because I don't know If I have ti import modules or just add these lines into app/build.gradle...

**Comment by skmlcd** [comment]
99% of the time you never include any files manually. Just add these lines into build.gradle, sync your project (click on button in toolbar, see image below) and it will include them for you.

![gradle](https://cloud.githubusercontent.com/assets/10860015/16396124/7996e6fe-3cbd-11e6-94c3-20b3f1737af3.png)

**Comment by juandiegoapps** [comment]
Ok. Now I'm going to do it. And If I just want to change the Image (in this case, of Pocket)?

**Comment by skmlcd** [comment]
Look at the example project that I linked in my first reply. This line of code is important ```.setImage(R.drawable.dummy_image)```

R.drawable.dummy_image this basically points to the image named _dummy\_image_ inside folder named _drawable_ in your project.

R.drawable.your_image_filename, but do **not** add any extension (.png / .jpg)

If you are new to Android in general then I suggest you check out this [guides](http://guides.codepath.com/android/Home#getting-started). Most of these things I said here are explained a lot better in these guides.

If you don't have any more problems with this specific library then please close this issue. :)
