### ISSUE TITLE
Dark Theme support

### ISSUE THREAD

**Issue by vanniktech** [medyo/android-about-page#62]
Would be cool to have a dark theme for this one as well.

**Comment by medyo** [comment]
Hi @vanniktech, Yes that would be a great feature, 
I think the right way to achieve it is by extending the default app theme, so the library could match any theme (Dark, Light or custom) and any style (Text SizeText Color, Background...)

What do you think about that ?

**Comment by vanniktech** [comment]
Yes I think that could be one solution another one would be maybe to rely on standard attributes to get the effect or provide a way to customize the theme / style. Dunno which one is best though. Another option would be to have `setBackground` / `setTextColor` / `setDividerColor` methods.

**Comment by medyo** [comment]
We'll mix both, auto handling current theme and also provide some setters to let developer override library styles in case of need.
