### ISSUE TITLE
setIntent

### ISSUE THREAD

**Issue by meddd** [medyo/android-about-page#74]
how to use setIntent, to start new activity

i used in Element:

Intent libIntent = new Intent(getBaseContext(), CustomInfoTosActivity.class);
        TossElement.setIntent(libIntent);

but it dosn work.

**Comment by medyo** [comment]
Hi @meddd,

make sure your intent is working, because the library does only launch that intent.

Here is a working sample : 

```
Intent websiteIntent = new Intent();
websiteIntent.setAction(Intent.ACTION_VIEW);
websiteIntent.addCategory(Intent.CATEGORY_BROWSABLE);
websiteIntent.setData(Uri.parse("http://github.com"));
webSiteElement.setIntent(websiteIntent);
```

Give it a try

**Comment by medyo** [comment]
any updates on this ?

**Comment by medyo** [comment]
Closed, if you still having the same issue, please reopen it
