### ISSUE TITLE
ActionBar Causes the about view to disapear in xamarin.android Help.

### ISSUE THREAD

**Issue by HamisiMickdad** [medyo/android-about-page#78]
I am trying to add an action bar to this activity but after adding it The actionbar shows but the view is blank in c#. Here is my code please help.
MY LAYOUT:

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/aboutdevelopers">
    <include
        android:id="@+id/toolbar"
        layout="@layout/toolbar" />
</LinearLayout>`

MY ACTIVITY:

`
using Android.App;
using Android.OS;
using Android.Support.V7.App;
using Android.Views;
using AndroidAboutPage;
using System;
using Toolbar = Android.Support.V7.Widget.Toolbar;
using Android.Widget;

namespace my_cards
{
    [Activity(Label = "About")]
    public class About : AppCompatActivity
    {
        LinearLayout mLinearLayout;

        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            SetContentView(Resource.Layout.about_Devs);
            var toolbar = FindViewById<Toolbar>(Resource.Id.toolbar);
            //Toolbar will now take on default actionbar characteristics
            SetSupportActionBar(toolbar);
            SupportActionBar.Title = "ABOUT US";
            SupportActionBar.SetDisplayHomeAsUpEnabled(true);
            SupportActionBar.SetHomeButtonEnabled(true);
            mLinearLayout = FindViewById<LinearLayout>(Resource.Id.aboutdevelopers);

            Element adsElement = new Element();
            adsElement.Title = "About US";
            View aboutPage = new AboutPage(this)
                .IsRTL(false)
                .SetImage(Resource.Drawable.splash_logo)
                .SetDescription("Here Is How To Contact The Dev Team")
                .AddItem(new Element() { Title = "Version 0.1" })
                .AddItem(adsElement)
                .AddGroup("Connect With Us")
                .AddEmail("hamisimickdad@gmail.com")
                .AddWebsite("http://lifeasy.azurewebsites.net")
                .AddFacebook("Hamisi Mickdad")
                .AddTwitter("@hmickdad")
                .AddYoutube("Hamisi Mickdad")
                .AddPlayStore("My Play")
                .AddInstagram("hmickdad")
                .AddGitHub("HamisiMickdad")
                .AddItem(CreateCopyright())
                .Create();
            // SetContentView(aboutPage);
            mLinearLayout.AddView(aboutPage, 1);
 }

        private Element CreateCopyright()
        {
            Element copyright = new Element();
            string copyrightString = $"Copyright {DateTime.Now.Year} by HamSoft";
            copyright.Title = copyrightString;
            copyright.Icon = Resource.Drawable.copyright;
            return copyright;
        }
        public override bool OnOptionsItemSelected(IMenuItem item)
        {
            if (item.ItemId == Android.Resource.Id.Home)
                Finish();

            return base.OnOptionsItemSelected(item);
        }

    }
}
`

**Comment by Kingamattack** [comment]
Having the same problem @HamisiMickdad, did you find a solution?
