### ISSUE TITLE
No way go back. Pressing back exits app.

### ISSUE THREAD

**Issue by ghost** [medyo/android-about-page#79]
Added about page to my app.
No way to go back to previous activity

**Comment by enight0000** [comment]
I meet the same question too

**Comment by medyo** [comment]
Hi Guys,

Could you share with me the `activity` code you used 

Thank you

**Comment by HaiDang666** [comment]
how to add back button for this

**Comment by attawit** [comment]
@Override
public void onBackPressed() {
   Intent inntent = new Intent(Intent.ACTION_MAIN);
   startActivity(setIntent);
}
 back press button how? please, if we are able to set onClickListener on Aboutpage , that will be helpful.   I have this question also,

**Comment by HaiDang666** [comment]
first you set theme of aboutActivity is ActionBar.
then use this code:
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ........
        // add back arrow to toolbar
        if (getSupportActionBar() != null){
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        }
    }

    @Override
    public boolean onSupportNavigateUp() {
        onBackPressed();
        return true;
    }
```

**Comment by Eight-For-Eight** [comment]
What does this sentence mean: "first you set theme of aboutActivity is ActionBar."? Is it set the them of aboutActivity to ActionBar or is it a typo and it is "set the theme of aboutActivity in ActionBar"?

I have the same issue - create an AboutPage (in the options menu) - select it, hit back press and the
app exits.  So (2) steps: set the theme then put in the override code. I'm going to put the override code
in and try to figure out the theme after. Thanks. I've tried so many things.

**Comment by Eight-For-Eight** [comment]
I can't make any of this code compile in my app where I have a main activity (fragment), or another fragment. The app is a variation of BluetoothChat and I can't get any of this code to compile no matter where I put it:

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ........
        // add back arrow to toolbar
        if (getSupportActionBar() != null){
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        }
    }

    @Override
    public boolean onSupportNavigateUp() {
        onBackPressed();
        return true;
    }

Two minutes to make the AboutPage and now 7 hours trying to make the back button not exit the app or, after visiting a web page from AboutPage how to make it not crash the app on back button.

Why is this so hard to do? It's useless without the back button and all the examples are toy programs that just display the about page as the app and back button exits the app.

**Comment by Eight-For-Eight** [comment]
I figured out a good, easy way to go back. This works for my main activity which extends a FragmentActivity, and AboutPage is presented from the options menu (with the dots). 

Basically I thought about it in terms of having a view and displaying it in a new activity. That led me to the basic android dev page Start Another Activity 

developer.android.com/training/basics/firstapp/starting-activity

I followed the tutorial but had to change the type of the activity generated from New Empty Activity from AppCompatActivity to FragmentActivity or the tutorial file would not compile.  Then I put the straight AboutPage code into this new activity.

The main issue is to not just fire up an AboutPage from an activity but to start a new activity with an intent and do it there. Now the about page goes back to the app (does not exit) and when returning from visiting the web page from the about page, it does not crash.

I think there may be many ways of hosting the about page and even though I tried a lot of things that didn't work it is probably my shallow android experience, rather than AboutPage which is great. Here's the code - first the options menu item:

```
case R.id.so_about: {

                // display the page!
                displayAboutPage();

                return true;
            }

```
```
/* Called when the user selects About option */
    public void displayAboutPage() {
        // Do something in response to button
        Intent intent = new Intent(this, DisplayAboutPageActivity.class);
        startActivity(intent);
    }
```

Then the activity:

public class DisplayAboutPageActivity extends FragmentActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_display_about_page);

        Element adsElement = new Element();
        adsElement.setTitle("Advertise with smartOar");
        String version = getResources().getString(R.string.app_version);

        View aboutPage = new AboutPage(this)
                .setDescription("armonitor is smartOar's real-time force curve feedback system utility product, based on Android")
                .isRTL(false)
                .addItem(new Element().setTitle(version))
                .addGroup("Connect with us")
                .addEmail("sales@smartoar.com")
                .addWebsite("http://www.smartoar.com")
                .addYoutube("UC1kgLzMza-NP21jiG8keztQ")
                .create();

        setContentView(aboutPage);
    }
}

**Comment by edwinmugendi** [comment]
Use TableLayout and then add the About Page as a view into the TableLayout

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_about);

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        if (getSupportActionBar() != null){
            getSupportActionBar().setTitle(getString(R.string.about_sapamacash));
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setDisplayShowHomeEnabled(true);
        }//E# if statement

        tableLayout = (TableLayout) findViewById(R.id.aboutLayout);

        String phone = "+254722906835";

        View aboutPage = new AboutPage(this)
                .isRTL(false)
                .setDescription(getString(R.string.about_us_text))
                .addEmail("info@sapamatech.com")
                .addItem(getPhoneElement(phone))
                .addWebsite("https://sapamacash.com/")
                .addFacebook("sapamatech")
                .addTwitter("sapamatech")
                .addYoutube("UCV-sIbWJ5HpO0qk6Hp7Sjfw")
                .addItem(getCopyRightsElement())
                .create();

        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);

        aboutPage.setLayoutParams(params);

        tableLayout.addView(aboutPage, 1,params);

    }



<?xml version="1.0" encoding="utf-8"?>
<TableLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    tools:context=".ui.activity.AboutActivity"
    android:id="@+id/aboutLayout">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="?attr/colorPrimary"
            app:layout_scrollFlags="scroll|enterAlways"/>

    </com.google.android.material.appbar.AppBarLayout>

</TableLayout>



```
