### ISSUE TITLE
Instagram support

### ISSUE THREAD

**Issue by filipmaelbrancke** [medyo/android-about-page#9]
Your description mentions Instagram support:
````
The library has already some predefined social networks like :  
* Facebook 
* Twitter
* Instagram
* Youtube
…	
addInstagram(String AccountID)
````

but I don't see it anywhere in the code. Do you want that as a pull request?

**Comment by medyo** [comment]
All resources are existing, I just forgot to add the method, it's added now 2bf4b65 ! Thanks again for your contributions
