### ISSUE TITLE
Add support for changing the page background color

### ISSUE THREAD

**Issue by omar753sahl** [medyo/android-about-page#92]

**Comment by medyo** [comment]
Hi @omar753sahl ,

That's doable by overriding the default style:

```
<style name="about_About.wrapper">
    <item name="android:layout_width">match_parent</item>
    <item name="android:layout_height">match_parent</item>
    <item name="android:orientation">vertical</item>
    <item name="android:gravity">center</item>
    <item name="android:background">#00ff00</item>
</style>
```

**Comment by wolftatoo** [comment]
@medyo 
Hi si Mehdi
i need to change the darkmode background color but i couldnt,
can you please save me this hustle and provide the java/xml code needed for that.
thank you
weld lblad!

**Comment by wolftatoo** [comment]
> @medyo
> Hi si Mehdi
> i need to change the darkmode background color but i couldnt,
> can you please save me this hustle and provide the java/xml code needed for that.
> thank you
> weld lblad!

**UPDATE:**
well..i have kinda figured it out, i did copy darkemode bg color from the "library" values.xml and pasted it in my apps colors.xml, editted it as i liked and called it done!
