### ISSUE TITLE
Suggestion: simple way of adding a pane to display open source licenses

### ISSUE THREAD

**Issue by jh3141** [medyo/android-about-page#96]
Various open source libraries include licenses that require apps using them to supply a copy of the license to the users, notices about the inclusion of the libraries, where to acquire copies of the source code, and other similar legal requirements.  The about page is a useful place to include such notices, probably in an expanding section so that the potentially large amount of text is usually hidden.  It would be nice if there were an easy way to include such a section in the page generated by this library.

**Comment by medyo** [comment]
Hi @jh3141,

At the moment, we don't support such feature, however, you could easily integrate AndroidAboutPage with https://github.com/mikepenz/AboutLibraries, which gives you details and licenses of the included libraries
