### ISSUE TITLE
Not able to open my facebook page through this library

### ISSUE THREAD

**Issue by shwtnk7** [medyo/android-about-page#99]
I am providing the page ID as the string input argument , but when i run the app and click on facebook , it does not open. Could you please check/provide your inputs on this ?

.addWebsite("www.google.com")
                **.addFacebook("1754981212131313")**
                .addTwitter("My Twitter")

**Comment by medyo** [comment]
Hi @shwtnk7,
Could you try using the page string id like `the.medy` (https://www.facebook.com/myId)

**Comment by medyo** [comment]
I'll close this issue now if you still having the same issue, please reopen it
